type Values = {
  pozo?: string;
  marcaVSD?: string;
  vsdPotencia?: string;
  vsdCorriente?: string;
  vsdEstadoSistemaVentilacion?: string;
  comunicacionSCADA?: string;
  marcaMotor?: string;
  motorPotencia?: string;
  motorCorriente?: string;
  numeroPolos?: string;
  motorVelocidadRPM?: string;
  marcaCabezal?: string;
  sistemaLubricacion?: string;
  modeloCabezal?: string;
  sNCabezal?: string;
  relacionPoleas?: string;
  controladorSAM?: string;
  tipo?: string;
  marca?: string;
  motorotador?: string;
  rotadorSobreRejillasContraPozo?: string;
  RPM?: string;
  corrienteMotor?: string;
  torqueBarraLisa?: string;
  torqueMotorPorcentaje?: string;
  presionLineaProduccionCabezaPozo?: string;
  presionLineaGasCabezaPozo?: string;
  cajaEmpaques?: string;
  inyeccionQuimico?: string;
  contraPozo?: string;
  altaTHP?: string;
  controlTorque?: string;
  altoTorque?: string;
  bajoTorque?: string;
  corrienteMaxima?: string;
  temperaturaVSD?: string;
  manometrica?: string;
  antecedentes?: string;
  observaciones?: string;
  fecha?: string;
};

type Data = Values[];
